### ISSUE TITLE
Openload.co plowdown : Invalid regular expreession

### ISSUE THREAD

**Issue by Izanagi52** [mcrapet/plowshare-modules-legacy#104]
Hello,
I have a problem when I try to download file from openload.co
When I try whith Spidermonkey 17 or 24 :

```
Starting download (openload): https://openload.co/f/u1I7LwGAplI/Test_file_5MiB.zip
Waiting 5 seconds... done
/tmp/plowdown.13624.32617.js:14:1 SyntaxError: unterminated regular expression literal:
/tmp/plowdown.13624.32617.js:14:1 </div>
/tmp/plowdown.13624.32617.js:14:1 .^
Output URL expected
```

And with nodejs (nodejs --version give me v0.10.29) :

```
Starting download (openload): https://openload.co/f/u1I7LwGAplI/Test_file_5MiB.zip
Waiting 5 seconds... done

/tmp/plowdown.14465.2167.js:14
</div>
 ^
SyntaxError: Invalid regular expression: missing /
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Output URL expected
```

I'm on a Raspberry Pi 3 with Raspbian Jessie

Thanks and sorry for my english, I'm french.

**Comment by hannsen** [comment]
rhino:

```
Starting download (openload): https://openload.co/f/u1I7LwGAplI/Test_file_5MiB.zip
Waiting 5 seconds... done
js: "/tmp/plowdown.6462.4342.js", line 14: unterminated regular expression literal
js: </div>
js: .....^
js: "/tmp/plowdown.6462.4342.js", line 1: Compilation produced 1 syntax errors.

```

**Comment by hannsen** [comment]
the js in question

```

attr = function(name,value) {
  if (typeof console === 'object' && typeof console.log === 'function') {
    console.log(value);
  } else {
    print(value);
  }
}
$ = function(obj) {
  return {
    attr: attr
  };
}
</div>
```

**Comment by hannsen** [comment]
sounds like the openload.sh doesnt parse the html right
