### ISSUE TITLE
RockFile Upload Broken

### ISSUE THREAD

**Issue by rlsblogse** [mcrapet/plowshare-modules-legacy#224]
hi,
rockfile use now clodflare , my uploading give me that error,
"Javascript interpreter not found. Please install one!"

so i install nodejs,  after that

uploading give me that error,

Waiting 5 seconds... done
/tmp/plowup.11786.3133.js:56
        f.action += location.hash;
                    ^

ReferenceError: location is not defined
    at /tmp/plowup.11786.3133.js:56:21
    at Object.<anonymous> (/tmp/plowup.11786.3133.js:63:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

regards
bye

**Comment by newmanifold** [comment]
try this
https://github.com/newmanifold/plowshare-modules-legacy/blob/master/rockfile_eu.sh

**Comment by rlsblogse** [comment]
hi,
thanks for quick response , its worked now, 

regards
