### ISSUE TITLE
TypeError: Cannot read property 'href' of undefined zippyshare

### ISSUE THREAD

**Issue by b1tb0x** [mcrapet/plowshare-modules-legacy#26]
plowdown http://www88.zippyshare.com/d/H31JUJJ6/10010/Artifuckt-Wild_Girl_EP-WNPR0089-WEB-2015-PITY.rar
Starting download (zippyshare): http://www88.zippyshare.com/d/H31JUJJ6/10010/Artifuckt-Wild_Girl_EP-WNPR0089-WEB-2015-PITY.rar
parse_attr failed (sed): "/id="omg"/ class="
Failed inside zippyshare_download(), line 149, zippyshare.sh

/tmp/plowdown.14068.15579.js:15
print(elts['fimage'].href);
^
TypeError: Cannot read property 'href' of undefined
at Object. (/tmp/plowdown.14068.15579.js:15:29)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3
Output URL is not valid: http://www88.zippyshare.com

I tried with http://www88.zippyshare.com/v/H31JUJJ6/file.html format as well

?

**Comment by Slashbunny** [comment]
:+1:
